### ISSUE TITLE
Can you limit character count

### ISSUE THREAD

**Issue by ellewiz** [cariad/wa11y.co#12]
I had to edit mine to cut back on the number of characters. Any way to thin out the “but’s and “and's” to reduce character count?

**Comment by cariad** [comment]
Hi! Can you share your Wordle result in a comment here so I've got a good example of one that's too long? Thanks!

**Comment by ellewiz** [comment]
Wordle 204 X/6
Line 1: 5th perfect, but 1st and 2nd in the wrong place.
Line 2: 5th perfect, but 3rd and 4th in the wrong place.
Line 3: 2nd and 5th perfect, but 1st in the wrong place.
Line 4: 2nd, 3rd and 5th perfect.
Line 5: 2nd, 3rd and 5th perfect.
Line 6: 2nd, 3rd, 4th and 5th perfect.

Edited for Twitter this way:

> Line 1: 5th perfect,1st and 2nd in the wrong place.
> Line 2: 5th perfect,3rd and 4th in the wrong place.
> Line 3: 2nd and 5th perfect, 1st in the wrong place.
> Line 4: 2nd, 3rd and 5th perfect.
> Line 5: 2nd, 3rd and 5th perfect.
> Line 6: 2nd, 3rd, 4th, 5th perfect.

Could simplify “in the wrong place” to “in wrong place” to save also, if that would make sense to screen readers.

**Comment by cariad** [comment]
Thanks! Can you share the full result including the emojis please?

I also just pushed up an update. Can you give it a try and see if it's fixed for you?

**Comment by ellewiz** [comment]
Wordle 204 X/6

🟨🟨⬜⬜🟩
⬜⬜🟨🟨🟩
🟨🟩⬜⬜🟩
⬜🟩🟩⬜🟩
⬜🟩🟩⬜🟩
⬜🟩🟩🟩🟩

Wordle 204 X/6

Line 1: 5th perfect. 1st and 2nd in the wrong place.
Line 2: 5th perfect. 3rd and 4th in the wrong place.
Line 3: 2nd and 5th perfect. 1st in the wrong place.
Line 4: 2nd, 3rd and 5th perfect.
Line 5: 2nd, 3rd and 5th perfect.
Line 6: 2nd, 3rd, 4th and 5th perfect.

Also just tried it again, and only 2 characters over this time.

**Comment by cariad** [comment]
Ah, I see it! The text already dynamically adjusts to fit within a tweet, but the calculation wasn't including the "Wordle 204 X/6" heading.

I just pushed up another update. Can you give it another try please?

**Comment by ellewiz** [comment]
Perfect!

> Wordle 204 X/6

> Line 1: 5th perfect. 1st & 2nd in the wrong place.
> Line 2: 5th perfect. 3rd & 4th in the wrong place.
> Line 3: 2nd & 5th perfect. 1st in the wrong place.
> Line 4: 2nd, 3rd & 5th perfect.
> Line 5: 2nd, 3rd & 5th perfect.
> Line 6: 2nd, 3rd, 4th & 5th perfect. 

With 10 characters left to go!

**Comment by cariad** [comment]
Fantastic! Thank you for raising this! :grin:
