### ISSUE TITLE
Portuguese version

### ISSUE THREAD

**Issue by anacuentro** [cariad/wa11y.co#18]
I loved this! I want to contribute (translation) to the Portuguese version because we have our http://term.ooo!

**Comment by cariad** [comment]
@anacuentro Hey, thank you! 

I'm a little bit scared of making non-critical changes to the app (especially in a language I can't read or support), but I do love this idea and I want to see it happen.

I think the best approach would be for you to fork and translate the project, find somewhere to host it if you can (it _should_ work in GitHub Pages, but I can provide hosting if you need it) and then I can point something like `pt.wa11y.co` (or any other subdomain you say is appropriate) at your version.

How does that sound to you? Of course, you should add yourself to the credit list on `index.html`! And I'm here to help if you need it.

**Comment by anacuentro** [comment]
@cariad Hey! 

I'm glad that you liked this idea! Yes, I agree with your suggestion. 
I'll try to do my very best.
Thank you!

**Comment by cariad** [comment]
@anacuentro Looks like you got your work up and running! Congratulations! :rocket: 

I'd like to point `pt.wa11y.co` at your published site, if that's okay?

If you're happy with that, you'll need to follow steps 1-4 and 9 under **[Configurando um subdomínio](https://docs.github.com/pt/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain)**/**[Configuring a subdomain](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain)** for your GitHub Pages.

I've already created the CNAME record, so the subdomain should start working within 24 hours of you making that change. Also, the instructions say enabling HTTPS is optional, but wa11y.co is configured to require HTTPS so it's _not_ optional. :grin: 

If you have any questions or problems, I'm here to help! :rocket:

**Comment by anacuentro** [comment]
>  Your site is ready to be published at http://pt.wa11y.co/

WOW! This is very amazing! 
I'm don't used with dev projects but I had fun. So I need to learn a lot about JS. 
Thanks so much!

**Comment by cariad** [comment]
Thank _you_! I really appreciate how you've taken this code and made something really useful out of it. :rocket:
