### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by EnduringBeta** [cariad/wa11y.co#9]
This is great, and you're fantastic for making it!

I use Chrome with uBlock, and I get these console errors when I load the page. When I turned off uBlock, the last 3 didn't show again, which makes sense.

The page works fine, but I wonder if I'm missing out on styles and such.

Also, is the page itself set up well for screen reader use? Just curious.

```
[Report Only] Refused to load the image 'data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>%F0%9F%8E%AE</text></svg>' because it violates the following Content Security Policy directive: "img-src https://cdn.usefathom.com/".

[Report Only] Refused to load the stylesheet 'https://wa11y.co/style.css?v=2.1' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'style-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

GET https://cdn.usefathom.com/script.js net::ERR_BLOCKED_BY_CLIENT
POST https://antagonist.report-uri.com/r/d/csp/reportOnly net::ERR_BLOCKED_BY_CLIENT
POST https://antagonist.report-uri.com/r/d/csp/reportOnly net::ERR_BLOCKED_BY_CLIENT
```

**Comment by cariad** [comment]
Ah, bother. Thanks! Those are just warnings, so you’re not actually missing anything, but I’ll get them sorted tomorrow. I appreciate it!

**Comment by cariad** [comment]
As for screen reader accessibility, I’m no expert but the advice I received in #4 seems sound!

**Comment by EnduringBeta** [comment]
Just perused #4, and great. Looks like you iterated on the page quite a bit. :+1:

**Comment by cariad** [comment]
@EnduringBeta Those console errors should be gone now. Let me know if anything else comes up -- and thanks for the report!
